workflow:
  - publish
  - prod

shared:
  image: node:6

jobs:
  main:
    steps:
      - install: npm install
      - bower: npm install bower && ./node_modules/.bin/bower install --allow-root
      - test: npm test

  # Publish the package to GitHub and build docker image
  publish:
    environment:
      RELEASE_FILE: sdui.tgz
      DOCKER_REPO: screwdrivercd/ui
    steps:
      - setup-ci: git clone https://gist.github.com/3d2388b2a7ba658cdcdaffa8cd874e50.git ci
      - install: npm install
      - bower: npm install bower && ./node_modules/.bin/bower install --allow-root
      - build: ./node_modules/.bin/ember build --environment production
      - package: tar -C dist -cvzf $RELEASE_FILE .
      - tag: ./ci/git-tag.sh
      - publish: ./ci/git-release.sh
      - docker: ./ci/docker.sh
    secrets:
      # Pushing tags to Git
      - GIT_KEY
      # Pushing releases to GitHub
      - GITHUB_TOKEN
      # Trigger a Docker Hub build
      - DOCKER_TRIGGER

  # Deploy to our prod environment and run tests
  prod:
    steps:
      - setup-ci: git clone https://gist.github.com/3d2388b2a7ba658cdcdaffa8cd874e50.git ci
      - wait-docker: DOCKER_TAG=`git describe --abbrev=0 --tags` ./ci/docker-wait.sh
      - deploy-k8s: K8S_TAG=`git describe --abbrev=0 --tags` ./ci/k8s-deploy.sh
      - test: echo Put acceptance tests here
    environment:
      DOCKER_REPO: screwdrivercd/ui
      K8S_CONTAINER: screwdriver-ui
      K8S_IMAGE: screwdrivercd/ui
      K8S_HOST: api.k8s.screwdriver.cd
      K8S_DEPLOYMENT: sdui
    secrets:
      # Talking to Kubernetes
      - K8S_TOKEN
